LoginDanLogout/urls.py
from django.urls import path
from LoginDanLogout.views import *

app_name = 'LoginDanLogout'

urlpatterns = [
    path('', show_main, name="show_main"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
]

Pengguna/urls.py
from django.urls import path
from Pengguna.views import *

app_name = 'Pengguna'

urlpatterns = [
    path("", register, name="register"),
]

Ulasan/urls.py
from django.urls import path
from Ulasan.views import *

apps = 'Ulasan'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('add_ulasan_film/', add_ulasan_film, name='add_ulasan_film'),
    path('add_ulasan_series/', add_ulasan_series, name='add_ulasan_series'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('langganan/', include('Langganan.urls')),
    path('favorit/', include('DaftarFavorit.urls')),
    path('kontributor/', include('daftarKontributor.urls')),
    path('unduhan/', include('DaftarUnduhan.urls')),
    path('', include('LoginDanLogout.urls')),
    path('register/', include('Pengguna.urls')),
    path('tayangan/', include('Tayangan.urls')),
    path('trailer/', include('Trailer.urls')),
    path('ulasan/', include('Ulasan.urls')),
]

LoginDanLogout/models.py
from django.db import models

# Create your models here.

LoginDanLogout/views.py
# views.py
import datetime
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.db.backends.utils import CursorWrapper
from utils.query import connectdb

@connectdb
@csrf_exempt
def login(cursor: CursorWrapper, request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        if not username or not password:
            messages.error(request, 'Username and password are required.')
        elif len(username) < 3 or len(password) < 6:
            messages.error(request, 'Username must be at least 3 characters and password must be at least 6 characters.')

        if not messages.get_messages(request):
            cursor.execute("SELECT * FROM pengguna WHERE username = %s AND password = %s", [username, password])
            user = cursor.fetchone()

            if user:
                request.session['username'] = username
                request.session['is_logged_in'] = True
                response = HttpResponseRedirect(reverse("Tayangan:show_tayangan"))
                response.set_cookie('username', username)
                response.set_cookie('negara_asal', user[2])
                response.set_cookie('last_login', str(datetime.datetime.now()))
                return response
            else:
                messages.error(request, 'Sorry, incorrect username or password. Please try again.')

    return render(request, 'login.html')

@csrf_exempt
def logout(request):
    response = HttpResponseRedirect(reverse('LoginDanLogout:show_main'))
    request.session.flush()
    response.delete_cookie('last_login')
    response.delete_cookie('username')
    response.delete_cookie('negara_asal')
    return response

def show_main(request):
    return render(request, "main.html")

LoginDanLogout/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="min-h-screen bg-[#242831] font-inter_tight">
    <div class="mb-12 text-slate-100 text-center">
        <h1 class="pt-16 pb-4 font-bold text-5xl drop-shadow-md">Login to <span class="bg-gradient-to-r from-red-500 to-pink-500 text-transparent bg-clip-text">PacilFlix</span></h1>
    </div>
    <div class="mx-auto max-w-sm">
        <form method="POST">
            {% csrf_token %}
            <div class="grid grid-cols-1 gap-y-7 text-white font-inter">
                <div>
                    <p class="text-sm font-bold mb-2">Username</p>
                    <input class="w-full rounded-lg border border-gray-500 px-4 py-3 bg-[#333845]" type="text" name="username" id="username" placeholder="Username">
                </div>
                <div>
                    <p class="text-sm font-bold mb-2">Password</p>
                    <input class="w-full rounded-lg border border-gray-500 px-4 py-3 bg-[#333845]" type="password" name="password" id="password" placeholder="Password" required>
                </div>
                <button type="submit" class="mt-5 w-full rounded-md font-bold text-black border px-12 py-4 bg-pink-500 hover:bg-pink-600 duration-300">Login</button>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p class="text-center text-sm text-red-500 mt-2">{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
    <div class="text-center text-white mt-12">
        <p>Don't have an account yet?</p>
        <a class="text-gray-400 hover:text-gray-300 duration-100" href="{% url 'Pengguna:register' %}">Create one.</a>
    </div>
</div>
{% endblock content %}

LoginDanLogout/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="mx-auto h-[calc(100vh-80px)]" style="background-color: #21242D; font-family: 'Lato', sans-serif; display: flex; flex-direction: column; justify-content: center; align-items: center;">
    <div class="text-center" style="color: #F9F9F9;">
        <h1 class="font-bold text-6xl drop-shadow-md"><span class="bg-gradient-to-r from-red-500 to-pink-500 text-transparent bg-clip-text">PacilFlix</span> - D6</h1>
    </div>
    <div class="flex flex-col gap-5">
        <a href="{% url 'LoginDanLogout:login' %}">
            <button type="submit" class="mt-5 w-full rounded-md font-bold text-black border px-24 py-4 bg-pink-500 hover:bg-pink-600 duration-300">Login</button>
        </a>
        <a href="{% url 'Pengguna:register' %}">
            <button type="submit" class="mt-5 w-full rounded-md font-bold text-black border px-24 py-4 bg-red-300 hover:bg-red-400  duration-300">Register</button>
        </a>
    </div>
</div>
{% endblock content %}