Tayangan/urls.py
from django.urls import path
from Tayangan.views import *

app_name = 'Tayangan'

urlpatterns = [
    path('', show_tayangan, name='show_tayangan'),
    path('search_tayangan/', show_search_tayangan, name='show_search_tayangan'),
    path('halaman_tayangan/', show_halaman_tayangan, name='show_halaman_tayangan'),
    path('film/', show_film, name='show_film'),
    path('series/', show_series, name='show_series'),
    path('episode/', show_episode, name='show_episode'),
]

Ulasan/urls.py
from django.urls import path
from Ulasan.views import *

apps = 'Ulasan'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('add_ulasan_film/', add_ulasan_film, name='add_ulasan_film'),
    path('add_ulasan_series/', add_ulasan_series, name='add_ulasan_series'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('langganan/', include('Langganan.urls')),
    path('favorit/', include('DaftarFavorit.urls')),
    path('kontributor/', include('daftarKontributor.urls')),
    path('unduhan/', include('DaftarUnduhan.urls')),
    path('', include('LoginDanLogout.urls')),
    path('register/', include('Pengguna.urls')),
    path('tayangan/', include('Tayangan.urls')),
    path('trailer/', include('Trailer.urls')),
    path('ulasan/', include('Ulasan.urls')),
]

Tayangan/models.py
from django.db import models

# Create your models here.

Tayangan/views.py
from django.db import connection
from django.http import JsonResponse
from utils.query import query
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

def show_tayangan(request):
    query_str = """SELECT generate_series(1, 10) AS peringkat, 
                        t.judul, 
                        t.sinopsis_trailer, 
                        t.url_video_trailer, 
                        t.release_date_trailer, 
                        generate_series(1, 10) AS total_view, t.id FROM TAYANGAN t LIMIT 10;"""
    hasil = query(query_str)

    query_str_film = "SELECT * FROM TAYANGAN JOIN FILM ON film.id_tayangan = tayangan.id;"
    hasil_film = query(query_str_film)
    query_str_series = "SELECT * FROM TAYANGAN JOIN SERIES ON series.id_tayangan = tayangan.id;"
    hasil_series = query(query_str_series)

    return render(request, 'tayangan.html', {'tayangans': hasil, 'tayangan_film': hasil_film, 'tayangan_series': hasil_series})

def show_search_tayangan(request):
    if request.method == 'GET':
        search_query = request.GET.get('search')
    query_str = f" SELECT tayangan.judul, tayangan.sinopsis_trailer, tayangan.url_video_trailer, tayangan.release_date_trailer FROM TAYANGAN WHERE tayangan.judul LIKE '%{search_query}%';"
    hasil = query(query_str)

    return render(request, 'search_tayangan.html', {'tayangans': hasil})

def show_halaman_tayangan(request):
    if request.method == 'POST':
        id_tayangan = request.POST.get('id_tayangan')
    with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM film WHERE id_tayangan = %s", [id_tayangan])
            film_count = cursor.fetchone()[0]

            cursor.execute("SELECT COUNT(*) FROM episode WHERE id_series = %s", [id_tayangan])
            episode_count = cursor.fetchone()[0]
    if film_count > 0:
        return redirect('Tayangan:show_film', id_film=id_tayangan)
    elif episode_count > 0:
        return redirect('Tayangan:show_series', id_series=id_tayangan)
    else:
        return redirect('page_not_found')
    
def show_film(request):
    if request.method == 'POST':
        id_film = request.POST.get('id_film')

    query_str = f"""
    SELECT 
        t.judul, 
        COUNT(*) AS total_view, 
        ROUND(AVG(u.rating), 2) AS rata_rata_rating, 
        t.sinopsis, 
        f.durasi_film, 
        f.release_date_film, 
        f.url_video_film, 
        ARRAY_AGG(DISTINCT gt.genre) AS genres, 
        t.asal_negara, 
        ARRAY_AGG(DISTINCT cp.nama) AS pemains, 
        ARRAY_AGG(DISTINCT cps.nama) AS penulis_skenario, 
        cs.nama AS sutradara
        f.id_tayangan
    FROM 
        TAYANGAN t 
    JOIN 
        FILM f ON f.id_tayangan = t.id 
    LEFT JOIN 
        RIWAYAT_NONTON rn ON rn.id_tayangan = t.id 
    LEFT JOIN 
        ULASAN u ON u.id_tayangan = t.id 
    LEFT JOIN 
        GENRE_TAYANGAN gt ON gt.id_tayangan = t.id 
    LEFT JOIN 
        MEMAINKAN_TAYANGAN mt ON mt.id_tayangan = t.id 
    LEFT JOIN 
        MENULIS_SKENARIO_TAYANGAN mst ON mst.id_tayangan = t.id 
    LEFT JOIN 
        CONTRIBUTORS cp ON cp.id = mt.id_pemain 
    LEFT JOIN 
        CONTRIBUTORS cps ON cps.id = mst.id_penulis_skenario 
    LEFT JOIN 
        CONTRIBUTORS cs ON cs.id = t.id_sutradara 
    WHERE 
        t.id = '{id_film}' 
    AND 
        EXTRACT(EPOCH FROM (rn.end_date_time - rn.start_date_time)) >= 0.7 * (
            CASE 
                WHEN f.id_tayangan IS NOT NULL THEN f.durasi_film * 60 
                ELSE 0 
            END
        )
    GROUP BY 
        t.judul, t.sinopsis, f.durasi_film, f.release_date_film, f.url_video_film, t.asal_negara, cs.nama;
    """

    hasil = query(query_str)
    query_str_ulasan = ''' SELECT ulasan.username, ulasan.deskripsi, ulasan.rating, ulasan.timestamp 
                    FROM ULASAN 
                    JOIN TAYANGAN ON tayangan.id = ulasan.id_tayangan
                    ORDER BY ulasan.timestamp DESC;
                '''
    hasil_ulasan = query(query_str_ulasan)
    for data in hasil_ulasan:
        data['formatted_timestamp'] = data['timestamp'].strftime("%Y-%m-%d %H:%M:%S")

    return render(request, 'film.html', {'films': hasil, 'ulasans':hasil_ulasan})

def show_series(request):
    if request.method == 'POST':
        id_series = request.POST.get('id_series')
    
    query_str = f"""
    SELECT 
        t.judul, 
        ARRAY_AGG(DISTINCT e.url_video) AS episodes, 
        COUNT(*) AS total_view, 
        ROUND(AVG(u.rating), 2) AS rata_rata_rating, 
        t.sinopsis, 
        ARRAY_AGG(DISTINCT gt.genre) AS genres, 
        t.asal_negara, 
        ARRAY_AGG(DISTINCT cp.nama) AS pemains, 
        ARRAY_AGG(DISTINCT cps.nama) AS penulis_skenario, 
        cs.nama AS sutradara
    FROM 
        TAYANGAN t 
    JOIN 
        SERIES s ON s.id_tayangan = t.id 
    LEFT JOIN 
        EPISODE e ON e.id_series = s.id_tayangan 
    LEFT JOIN 
        RIWAYAT_NONTON rn ON rn.id_tayangan = t.id 
    LEFT JOIN 
        ULASAN u ON u.id_tayangan = t.id 
    LEFT JOIN 
        GENRE_TAYANGAN gt ON gt.id_tayangan = t.id 
    LEFT JOIN 
        MEMAINKAN_TAYANGAN mt ON mt.id_tayangan = t.id 
    LEFT JOIN 
        MENULIS_SKENARIO_TAYANGAN mst ON mst.id_tayangan = t.id 
    LEFT JOIN 
        CONTRIBUTORS cp ON cp.id = mt.id_pemain 
    LEFT JOIN 
        CONTRIBUTORS cps ON cps.id = mst.id_penulis_skenario 
    LEFT JOIN 
        CONTRIBUTORS cs ON cs.id = t.id_sutradara 
    WHERE 
        s.id_tayangan = '{id_series}'
    AND 
        EXTRACT(EPOCH FROM (rn.end_date_time - rn.start_date_time)) >= 0.7 * (
            CASE 
                WHEN s.id_tayangan IS NOT NULL THEN SUM(e.durasi) * 60 
                ELSE 0 
            END
        )
    GROUP BY 
        t.judul, t.sinopsis, t.asal_negara, cs.nama, total_view;
    """
    
    hasil = query(query_str)
    # for data in hasil:
    #     data['formatted_timestamp'] = data['timestamp'].strftime("%Y-%m-%d %H:%M:%S")
    return render(request, 'series.html', {'series': hasil})

def show_episode(request):
    if request.method == 'POST':
        sub_judul = request.POST.get('sub_judul')
    query_str = f" SELECT t.judul, e1.sub_judul, ARRAY_AGG(e.url_video), e1.sinopsis, e1.durasi, e1.url_video, e1.release_date FROM TAYANGAN t JOIN SERIES s ON s.id_tayangan = t.id JOIN EPISODE e ON e.id_series = s.id_tayangan JOIN EPISODE e1 ON e1.sub_judul = '{sub_judul}';"
    hasil = query(query_str)
    # for data in hasil:
    #     data['formatted_timestamp'] = data['timestamp'].strftime("%Y-%m-%d %H:%M:%S")
    return render(request, 'episode.html', {'episode': hasil})

Tayangan/templates/episode.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Halaman Series</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #242831;
            color: #e4e6eb;
            margin: 0;
            padding: 0;
        }
        h1, h2 {
            text-align: center;
            font-size: 4xl;
            font-weight: bold;
            margin-bottom: 8px;
        }
        button, input[type="number"], input[type="text"] {
            background-color: #333845;
            border: 1px solid #777;
            color: white;
            padding: 8px 12px;
            margin: 5px;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        button:hover {
            background-color: #d14f4f;
        }
        ul {
            list-style: none;
            padding-left: 0;
        }
        li {
            margin-bottom: 5px;
        }
        a {
            color: #e4e6eb;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .container {
            width: 90%;
            margin: auto;
            padding: 20px;
            background-color: #333845;
            border-radius: 8px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #333845;
        }
        th, td {
            padding: 8px;
            border: 1px solid #777;
            color: white;
        }
        th {
            background-color: #50555c;
            text-align: center;
        }
        td {
            text-align: left;
        }
        .info-label {
            font-weight: bold;
            margin-right: 5px;
        }
        
    </style>
</head>
<body>
    {% for film in series %}
    <div class="film-details">
        <h1>Judul: <span id="judul">{{ film.judul }}</span></h1>
    </div>
    <div class="film-details">
        <h1>Sub Judul: <span id="sub_judul">{{ film.sub_judul }}</span></h1>
    </div>
    <div class="section">
        <p>Episode:</p>
        <ul id="episode">
            {% for episode in film.episodes %}
                <li>{{ episode }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="divider">
        ▬▬▬▬▬▬▬▬▬▬▬▬▬⚫-----------------------------------------
    </div>

    <div class="buttons">
        <button id="tonton">Tonton</button>
    </div>

    <div class="section">
        <p>Sinopsis Episode: <span id="sinopsis">{{ film.sinopsis }}</span></p>
        <p>Durasi Episode: <span id="durasi">{{ film.durasi_film }}</span></p>
        <p>URL Episode: <a href="#" id="url-film">{{ film.url_video }}</a></p>
        <p>Tanggal Rilis Episode: <span id="tanggal-rilis">{{ film.release_date_film }}</span></p>
    </div>

</body>
</html>

{% endblock content %}

Tayangan/templates/film.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Halaman Film</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #242831;
            color: #e4e6eb;
            margin: 0;
            padding: 0;
        }
        h1, h2 {
            text-align: center;
            font-size: 4xl;
            font-weight: bold;
            margin-bottom: 8px;
        }
        button, input[type="number"], input[type="text"] {
            background-color: #333845;
            border: 1px solid #777;
            color: white;
            padding: 8px 12px;
            margin: 5px;
            border-radius: 8px;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        button:hover {
            background-color: #d14f4f;
        }
        ul {
            list-style: none;
            padding-left: 0;
        }
        li {
            margin-bottom: 5px;
        }
        a {
            color: #e4e6eb;
            text-decoration: none;
        }
        a:hover {
            text-decoration: underline;
        }
        .container {
            width: 90%;
            margin: auto;
            padding: 20px;
            background-color: #333845;
            border-radius: 8px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #333845;
        }
        th, td {
            padding: 8px;
            border: 1px solid #777;
            color: white;
        }
        th {
            background-color: #50555c;
            text-align: center;
        }
        td {
            text-align: left;
        }
        .info-label {
            font-weight: bold;
            margin-right: 5px;
        }
        
    </style>
</head>
<body>
    {% for film in films %}
    <div class="film-details">
        <h1>Judul: <span id="judul">{{ film.judul }}</span></h1>
    </div>

    <div class="divider">
        ▬▬▬▬▬▬▬▬▬▬▬▬▬⚫-----------------------------------------
    </div>

    <div class="buttons">
        <button id="tonton">Tonton</button>
        <button id="unduh">Unduh Tayangan</button>
        <button id="favorit">Favorit Tayangan</button>
    </div>

    <div class="section">
        <p>Total View: <span id="total-view">{{ film.total_view }}</span></p>
        <p>Rating Rata-Rata: <span id="rating">{{ film.rata_rata_rating }}</span></p>
        <p>Sinopsis: <span id="sinopsis">{{ film.sinopsis }}</span></p>
        <p>Durasi Film: <span id="durasi">{{ film.durasi_film }}</span></p>
        <p>Tanggal Rilis Film: <span id="tanggal-rilis">{{ film.release_date_film }}</span></p>
        <p>URL Film: <a href="#" id="url-film">{{ film.url_video }}</a></p>
    </div>

    <div class="section">
        <p>Genre:</p>
        <ul id="genre">
            {% for genre in film.genres %}
                <li>{{ genre }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="section">
        <p>Asal Negara: <span id="asal-negara">{{ film.asal_negara }}</span></p>
    </div>

    <div class="section">
        <p>Pemain:</p>
        <ul id="pemain">
            {% for pemain in film.pemains %}
                <li>{{ pemain }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="section">
        <p>Penulis Skenario:</p>
        <ul id="penulis-skenario">
            {% for penulis in film.penulis_skenario %}
                <li>{{ penulis }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="section">
        <p>Sutradara: <span id="sutradara">{{ film.sutradara }}</span></p>
    </div>
    {% endfor %}

    <div class="section" id="ulasan">
        <h2>Bagian Ulasan</h2>
    </div>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Rating</th>
                <th>Deskripsi</th>
            </tr>
        </thead>
        <tbody>
            {% for ulasan in ulasans %}
            <tr class="border-t border-gray-700">
                <td>{{ ulasan.username }}</td>
                <td>{{ ulasan.rating }}</td>
                <td>{{ ulasan.deskripsi }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Tidak ada ulasan yang ditemukan.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% for film in films %}
    <form action="{% url 'Ulasan:add_ulasan' %}" method="post" class="flex justify-center mb-8">
        {% csrf_token %}
        <input type="hidden" name="id_film" value="{{ film.id_tayangan }}">
        <input type="number" id="rating" name="rating" min="1" max="5">
        <input class="w-full rounded-lg border border-gray-500 px-4 py-3 bg-[#333845]" type="text" name="deskripsi" id="deskripsi" placeholder="Ulasan anda terhadap film ini ...">
        <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Tambah</button>
    </form>
    {% endfor %}

</body>
</html>

{% endblock content %}

Tayangan/templates/search.html
{% extends 'base.html' %}

{% block content %}
<div class="min-h-screen bg-[#242831] text-slate-100 font-inter">
    <div class="container mx-auto py-12 px-4">
        <h2 class="text-center text-4xl font-bold mb-8">Pencarian</h2>

        <form method="get" class="flex justify-center mb-8">
            <input type="text" name="search" value="{{ query }}" placeholder="Cari tayangan...">
            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Cari</button>
        </form>

        <style>
            table {
                border-collapse: collapse;
                width: 100%;
                background-color: #333845; /* Slightly darker table background */
            }
            th, td {
                border: 1px solid #777; /* Lighter border color */
                padding: 8px;
                text-align: left;
                color: white; /* White text color for readability */
            }
            th {
                background-color: #50555c; /* Darker header background */
            }
        </style>
        <table>
            <thead>
                <tr>
                    <th>Judul</th>
                    <th>Sinopsis Trailer</th>
                    <th>URL Trailer</th>
                    <th>Tanggal Rilis Trailer</th>
                    <th>Tayangan</th>
                </tr>
            </thead>
            <tbody>
                {% for trailer in trailers %}
                <tr class="border-t border-gray-700">
                    <td>{{ trailer.judul }}</td>
                    <td>{{ trailer.sinopsis_trailer }}</td>
                    <td>{{ trailer.url_video_trailer }}</td>
                    <td>{{ trailer.formatted_timestamp }}</td>
                    <td>
                        <form action="{% url 'show_film' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="id_tayangan" value="{{ trailer.id }}">
                            <button type="submit" class="button">Tayangan</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Tidak ada tayangan yang ditemukan.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

Tayangan/templates/search_tayangan.html
{% extends 'base.html' %}

{% block content %}
<div class="min-h-screen bg-[#242831] text-slate-100 font-inter">
    <div class="container mx-auto py-12 px-4">
        <h2 class="text-center text-4xl font-bold mb-8">Pencarian</h2>

        <form method="get" class="flex justify-center mb-8">
            <input type="text" name="search" placeholder="Cari tayangan..." class="bg-[#333845] text-white border border-gray-700 p-2 rounded">
            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Cari</button>
        </form>

        <style>
            table {
                border-collapse: collapse;
                width: 100%;
                background-color: #333845; /* Slightly darker table background */
            }
            th, td {
                border: 1px solid #777; /* Lighter border color */
                padding: 8px;
                text-align: left;
                color: white; /* White text color for readability */
            }
            th {
                background-color: #50555c; /* Darker header background */
            }
        </style>
        <table>
            <thead>
                <tr>
                    <th>Judul</th>
                    <th>Sinopsis Trailer</th>
                    <th>URL Trailer</th>
                    <th>Tanggal Rilis Trailer</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for trailer in tayangans %}
                <tr class="border-t border-gray-700">
                    <td>{{ trailer.judul }}</td>
                    <td>{{ trailer.sinopsis_trailer }}</td>
                    <td>{{ trailer.url_video_trailer }}</td>
                    <td>{{ trailer.release_date_trailer }}</td>
                    <td>
                        <form action="{% url 'Tayangan:show_halaman_tayangan' %}" method="post" class="flex justify-center mb-8">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ trailer.id }}">
                            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Tonton</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Tidak ada tayangan yang ditemukan.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

Tayangan/templates/tayangan.html
{% extends 'base.html' %}

{% block content %}
<div class="min-h-screen bg-[#242831] text-slate-100 font-inter">
    <div class="container mx-auto py-12 px-4">
        <h2 class="text-center text-4xl font-bold mb-8">Daftar Tayangan</h2>

        <form action="{% url 'Tayangan:show_search_tayangan' %}" method="get" class="flex justify-center mb-8">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Cari tayangan..." class="bg-[#333845] text-white border border-gray-700 p-2 rounded">
            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Cari</button>
        </form>

        <style>
            table {
                border-collapse: collapse;
                width: 100%;
                background-color: #333845; /* Slightly darker table background */
            }
            th, td {
                border: 1px solid #777; /* Lighter border color */
                padding: 8px;
                text-align: left;
                color: white; /* White text color for readability */
            }
            th {
                background-color: #50555c; /* Darker header background */
            }
        </style>
        <div class="flex justify-center mb-4">
            <form method="get" class="button">
                <button class="bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded mr-4">Top 10 Global</button>
            </form>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Peringkat</th>
                    <th>Judul</th>
                    <th>Sinopsis Trailer</th>
                    <th>URL Trailer</th>
                    <th>Tanggal Rilis Trailer</th>
                    <th>Total View 7 Hari Terakhir</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for trailer in tayangans %}
                <tr class="border-t border-gray-700">
                    <td>{{ trailer.peringkat }}</td>
                    <td>{{ trailer.judul }}</td>
                    <td>{{ trailer.sinopsis_trailer }}</td>
                    <td>{{ trailer.url_video_trailer }}</td>
                    <td>{{ trailer.release_date_trailer }}</td>
                    <td>{{ trailer.total_view }}</td>
                    <td>
                        <form action="{% url 'Tayangan:show_halaman_tayangan' %}" method="post" class="flex justify-center mb-8">
                            {% csrf_token %}
                            <input type="hidden" name="id_tayangan" value="{{ trailer.id }}">
                            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Tonton</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Tidak ada tayangan yang ditonton selama seminggu terakhir.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table><br>
        <h3 class="text-center text-4xl font-bold mb-8">Film</h3>
        <table>
            <thead>
                <tr>
                    <th>Judul</th>
                    <th>Sinopsis Trailer</th>
                    <th>URL Trailer</th>
                    <th>Tanggal Rilis Trailer</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for trailer in films %}
                <tr class="border-t border-gray-700">
                    <td>{{ trailer.judul }}</td>
                    <td>{{ trailer.sinopsis_trailer }}</td>
                    <td>{{ trailer.url_video_trailer }}</td>
                    <td>{{ trailer.release_date_trailer }}</td>
                    <td>
                        <form action="{% url 'Tayangan:show_film' %}" method="post" class="flex justify-center mb-8">
                            {% csrf_token %}
                            <input type="hidden" name="id_film" value="{{ trailer.id }}">
                            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Tonton</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Tidak ada film yang ditemukan.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table><br>
        <h3 class="text-center text-4xl font-bold mb-8">Series</h3>
        <table>
            <thead>
                <tr>
                    <th>Judul</th>
                    <th>Sinopsis Trailer</th>
                    <th>URL Trailer</th>
                    <th>Tanggal Rilis Trailer</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for trailer in series %}
                <tr class="border-t border-gray-700">
                    <td>{{ trailer.judul }}</td>
                    <td>{{ trailer.sinopsis_trailer }}</td>
                    <td>{{ trailer.url_video_trailer }}</td>
                    <td>{{ trailer.release_date_trailer }}</td>
                    <td>
                        <form action="{% url 'Tayangan:show_series' %}" method="post" class="flex justify-center mb-8">
                            {% csrf_token %}
                            <input type="hidden" name="id_series" value="{{ trailer.id }}">
                            <button type="submit" class="ml-4 bg-pink-500 hover:bg-red-500 text-white font-bold py-2 px-4 rounded">Tonton</button>
                        </form>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Tidak ada series yang ditemukan.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}